development:
  secret_key_base: <%= ENV['secret_key_base'] %>
  app_name: '[CTRL]ALT'
  app_url: <%= ENV['app_url'] %>
  return_street1: <%= ENV['return_street1'] %>
  return_street2: <%= ENV['return_street2'] %>
  return_city: <%= ENV['return_city'] %>
  return_zip: <%= ENV['return_zip'] %>
  return_state: <%= ENV['return_state'] %>
  return_country: <%= ENV['return_country'] %>
  return_phone: <%= ENV['return_phone'] %>
  easypost_key: <%= ENV['easypost_key'] %>
  aws_key: <%= ENV['aws_key'] %>
  aws_secret: <%= ENV['aws_secret'] %>
  aws_region: <%= ENV['aws_region'] %>
  aws_fog_directory: <%= ENV['aws_fog_directory'] %>
  aws_asset_host: <%= ENV['aws_asset_host'] %>
  stripe_email: <%= ENV['stripe_email'] %>
  stripe_secret_key: <%= ENV['stripe_secret_key'] %>
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %>
  mailchimp_api_key: <%= ENV['mailchimp_api_key'] %>
  mailchimp_list_id: <%= ENV['mailchimp_list_id'] %>
  mandrill_domain: <%= ENV['mandrill_domain'] %>
  mandrill_username: <%= ENV['mandrill_username'] %>
  mandrill_password: <%= ENV['mandrill_password'] %>
  action_mailer_host: <%= ENV['action_mailer_host'] %>
  action_mailer_asset_host: <%= ENV['action_mailer_asset_host'] %>
production:
  secret_key_base: <%= ENV['secret_key_base'] %>
  app_name: '[CTRL]ALT'
  app_url: <%= ENV['app_url'] %>
  easypost_key: <%= ENV['easypost_key'] %>
  aws_key: <%= ENV['aws_key'] %>
  aws_secret: <%= ENV['aws_secret'] %>
  aws_region: <%= ENV['aws_region'] %>
  aws_fog_directory: <%= ENV['aws_fog_directory'] %>
  aws_asset_host: <%= ENV['aws_asset_host'] %>
  stripe_email: <%= ENV['stripe_email'] %>
  stripe_secret_key: <%= ENV['stripe_secret_key'] %>
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %>
  mailchimp_api_key: <%= ENV['mailchimp_api_key'] %>
  mailchimp_list_id: <%= ENV['mailchimp_list_id'] %>
  mandrill_domain: <%= ENV['mandrill_domain'] %>
  mandrill_username: <%= ENV['mandrill_username'] %>
  mandrill_password: <%= ENV['mandrill_password'] %>
  action_mailer_host: <%= ENV['action_mailer_host'] %>
  action_mailer_asset_host: <%= ENV['action_mailer_asset_host'] %>
test:
  secret_key_base: <%= ENV['secret_key_base'] %>